"""add player_stats

Revision ID: 8da2d054d53f
Revises: bd88730d13be
Create Date: 2025-12-21 16:23:59.907092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da2d054d53f'
down_revision: Union[str, Sequence[str], None] = 'bd88730d13be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hands_won', sa.Integer(), nullable=False),
    sa.Column('hands_lost', sa.Integer(), nullable=False),
    sa.Column('max_balance', sa.BigInteger(), nullable=False),
    sa.Column('max_bet', sa.BigInteger(), nullable=False),
    sa.Column('lost_stack', sa.BigInteger(), nullable=False),
    sa.Column('won_stack', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_player_stats_user_id'), 'player_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_user_id'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
